// Copyright 2022-2026 Nikita Fediuchin. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Physically based atmosphere ambient light.

#extension GL_KHR_shader_subgroup_arithmetic : enable

spec const uint32 SG_SHARED_SIZE = 16;

#include "atmosphere/common.gsl"
#include "common/brdf.gsl"
#include "common/normal-mapping.gsl"

#ifdef GL_KHR_shader_subgroup_arithmetic
#define AL_SHARED_SIZE SG_SHARED_SIZE
#else
#define AL_SHARED_SIZE AL_WG_LOCAL_SIZE
#endif

localSize = 8, 8, 1;

uniform sampler2D
{
	filter = linear;
} transLUT;
uniform sampler2D
{
	filter = linear;
} skyViewLUT;

buffer writeonly noncoherent restrict std430 SkyBuffer
{
	float4 data[];
} sky;

uniform pushConstants
{
	float3 cameraPos;
	float bottomRadius;
	float3 starDir;
	float topRadius;
	float3 starColor;
	uint32 dataOffset;
} pc;

shared float3 ambientShared[AL_SHARED_SIZE];

//**********************************************************************************************************************
void main()
{
	uint32 localThreadID = gl.localInvocationIndex;
	float3x3 tbn = approximateTBN(normalize(pc.cameraPos));
	float2 u = hammersley(localThreadID, (1.0f / AL_WG_LOCAL_SIZE));
	float3 worldDir = tbn * sampleHemisphereCosine(u);
	float2 uv = skyViewToUV(skyViewLUT, pc.cameraPos, pc.bottomRadius, pc.starDir, worldDir);
	float3 skyColor = textureLod(skyViewLUT, uv, 0.0f).rgb;

#ifdef GL_KHR_shader_subgroup_arithmetic
	float3 ambientSum = subgroupAdd(skyColor);
	if (subgroupElect())
		ambientShared[gl.subgroupID] = ambientSum;
	barrier();
#else
	ambientShared[localThreadID] = skyColor;
	barrier();

	for (uint32 stride = (AL_WG_LOCAL_SIZE >> 1); stride > 0; stride >>= 1)
	{
		ambientShared[localThreadID] += localThreadID < stride ? 
			ambientShared[localThreadID + stride] : float3(0.0f);
		barrier();
	}
#endif

	if (localThreadID == 0)
	{
		float3 ambientLight = ambientShared[0];
#ifdef GL_KHR_shader_subgroup_arithmetic
		for (uint32 i = 1; i < SG_SHARED_SIZE; i++)
			ambientLight += ambientShared[i];
#endif
		ambientLight *= (M_PI / AL_WG_LOCAL_SIZE);
		sky.data[pc.dataOffset].xyz = ambientLight;

		float3 transmittance = getTransmittance(transLUT, Ray(
			pc.cameraPos, pc.starDir), pc.bottomRadius, pc.topRadius);
		sky.data[pc.dataOffset + 1].xyz = transmittance * pc.starColor;
	}
}